name= "pastebin-worker"
compatibility_date = "2023-12-12"
account_id= "def29e6f33488ff3f2f4b4c0b0ea1503"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "pb.eeeee.cf", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "de87556776f6465ba4c723472cd1e18e" },
  { binding = "PBIMGS", id ="c710406e0acf4c7ba7741018ed2aff70" }
]

[site]
bucket = "./static/dist"
